#!/usr/bin/env bash

DOCKER_IMAGE_PREFIX="ivanfranchin"
APP_VERSION="1.0.0"

PRODUCER_CLOUD_STREAM_APP_NAME="producer-cloud-stream"
CONSUMER_CLOUD_STREAM_APP_NAME="consumer-cloud-stream"

PRODUCER_CLOUD_STREAM_PROJECT_NAME="spring-cloud-stream/${PRODUCER_CLOUD_STREAM_APP_NAME}"
CONSUMER_CLOUD_STREAM_PROJECT_NAME="spring-cloud-stream/${CONSUMER_CLOUD_STREAM_APP_NAME}"

PRODUCER_CLOUD_STREAM_DOCKER_IMAGE_NAME="${DOCKER_IMAGE_PREFIX}/${PRODUCER_CLOUD_STREAM_APP_NAME}:${APP_VERSION}"
CONSUMER_CLOUD_STREAM_DOCKER_IMAGE_NAME="${DOCKER_IMAGE_PREFIX}/${CONSUMER_CLOUD_STREAM_APP_NAME}:${APP_VERSION}"

SKIP_TESTS="true"

./mvnw clean compile jib:dockerBuild \
  --projects "$PRODUCER_CLOUD_STREAM_PROJECT_NAME" \
  -DskipTests="$SKIP_TESTS" \
  -Dimage="$PRODUCER_CLOUD_STREAM_DOCKER_IMAGE_NAME"

./mvnw clean compile jib:dockerBuild \
  --projects "$CONSUMER_CLOUD_STREAM_PROJECT_NAME" \
  -DskipTests="$SKIP_TESTS" \
  -Dimage="$CONSUMER_CLOUD_STREAM_DOCKER_IMAGE_NAME"
